### ISSUE TITLE
Missing intermediate certificate

### ISSUE THREAD

**Issue by c7hm4r** [strukturag/iridium-browser-ubuntu#10]
The page [https://downloads.iridiumbrowser.de/](https://downloads.iridiumbrowser.de/) has an incomplete certificate chain. Ubuntu 16.04 does not have the intermediate certificate for letsencrypt in its certificate authority store, so `curl` or `wget` will fail. That is why the instruction at [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html) for Ubuntu do not work. See also [SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=downloads.iridiumbrowser.de&s=88.198.180.164&latest).

**Comment by longsleep** [comment]
This should no longer be a problem.
