### ISSUE TITLE
Synaptic: Wrong sources.list entry or malformed file

### ISSUE THREAD

**Issue by GeorgeSalt** [strukturag/iridium-browser-ubuntu#11]
I'm running Linux Mint 17.3 (64-bit).

When I attempt to update, Synaptic reports:

> Conflicting distribution: http://downloads.iridiumbrowser.de trusty InRelease (expected trusty but got stable)Failed to fetch http://downloads.iridiumbrowser.de/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
> Some index files failed to download. They have been ignored, or old ones used instead.

I believe 'main/binary-i386/Packages' should be 'main/binary-amd64/Packages'

**Comment by longsleep** [comment]
This is just a warning as the repository contains no i386 packages and provides a single package for all debian based distros.

To get rid of the warnings replace `trusty` with `stable` and add `[arch=amd64]` after the `deb` keywoard in your sources list.

```
cat /etc/apt/sources.list.d/iridium-browser.list
deb [arch=amd64] https://downloads.iridiumbrowser.de/deb/ stable main
# deb-src [arch=amd64] https://downloads.iridiumbrowser.de/deb/ stable main
```

**Comment by GeorgeSalt** [comment]
Works.  Thanks.
