### ISSUE TITLE
default search engine change to google:- crashes the browser

### ISSUE THREAD

**Issue by d-vineet** [strukturag/iridium-browser-ubuntu#13]
My OS is Ubuntu 16.04 LTS.
Intel® Core™ i3-2328M CPU @ 2.20GHz × 4.
Installed Iridium and it is working fine.
*Issue faced --* 
When tried to change the default search engine to "google"  (from *"settings" -- "Manage search engines"*), the browser crashes.
But it works fine if tried to set the search engine to others such as bing.
(although I am not a lover of google, but still I thought I should report this).
Not sure if this is a bug or is it on purpose.

**Comment by medozas** [comment]
fixed in 2017.11.1
