### ISSUE TITLE
Iridium not starting

### ISSUE THREAD

**Issue by choelzl** [strukturag/iridium-browser-ubuntu#14]
Running iridium-browser on:

> 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
Version 2018.5 (Developer Build) Built on Ubuntu 16.04, running on Debian testing (64-bit)

Error Displayed when trying to run iridium:

> [19094:19094:0530/120543.747985:FATAL:zygote_host_impl_linux.cc(124)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x556d0daa486c <unknown>
#1 0x556d0dabc39e <unknown>
#2 0x556d0c851619 <unknown>
#3 0x556d0d6abc0d <unknown>
#4 0x556d0d6b5999 <unknown>
#5 0x556d0d6aa364 <unknown>
#6 0x556d0b9e31d3 ChromeMain
#7 0x7ffb2af22a87 __libc_start_main
#8 0x556d0b9e3049 _start
Received signal 6
#0 0x556d0daa486c <unknown>
#1 0x556d0daa43c1 <unknown>
#2 0x7ffb31b59f50 <unknown>
#3 0x7ffb2af35e7b gsignal
#4 0x7ffb2af37231 abort
#5 0x556d0daa2ad5 <unknown>
#6 0x556d0dabc68c <unknown>
#7 0x556d0c851619 <unknown>
#8 0x556d0d6abc0d <unknown>
#9 0x556d0d6b5999 <unknown>
#10 0x556d0d6aa364 <unknown>
#11 0x556d0b9e31d3 ChromeMain
#12 0x7ffb2af22a87 __libc_start_main
#13 0x556d0b9e3049 _start
  r8: 0000000000000000  r9: 00007ffe46c21310 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffb2b853080 r13: 00007ffe46c21a28 r14: 000000000000016d r15: 00007ffe46c21a20
  di: 0000000000000002  si: 00007ffe46c21310  bp: 00007ffe46c21560  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007ffb2af35e7b  sp: 00007ffe46c21310
  ip: 00007ffb2af35e7b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

Using the --no-sandbox arg seems to work...

 The release shouldn't be compiled with the development sandbox activated:

> IMPORTANT NOTE: The Linux SUID sandbox is almost but not completely removed. See https://bugs.chromium.org/p/chromium/issues/detail?id=598454 This page is mostly out-of-date.

**Comment by longsleep** [comment]
See https://github.com/iridium-browser/tracker/issues/208 - closing this here.
